"""Add auto-navigation fields to Tournament model

Revision ID: 059435531149
Revises: de039fdee910
Create Date: 2025-05-18 07:58:28.430226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059435531149'
down_revision = 'de039fdee910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('auto_navigate', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tournament', sa.Column('auto_navigate_delay', sa.Integer(), server_default='30', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'auto_navigate_delay')
    op.drop_column('tournament', 'auto_navigate')
    # ### end Alembic commands ###
