"""Add external_id and other fields to Team and Participant models

Revision ID: 2dff249d8e9f
Revises: 9121047b7940
Create Date: 2025-05-10 16:39:23.107975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dff249d8e9f'
down_revision = '9121047b7940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('external_id', sa.String(length=50), nullable=True))
    op.add_column('participant', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('participant', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('participant', sa.Column('display_name', sa.String(length=160), nullable=True))
    op.add_column('team', sa.Column('external_id', sa.String(length=50), nullable=True))
    op.add_column('team', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('team', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'notes')
    op.drop_column('team', 'source')
    op.drop_column('team', 'external_id')
    op.drop_column('participant', 'display_name')
    op.drop_column('participant', 'notes')
    op.drop_column('participant', 'source')
    op.drop_column('participant', 'external_id')
    # ### end Alembic commands ###
