"""Add is_default flag to Tournament

Revision ID: cabceaa5a966
Revises: 2dff249d8e9f
Create Date: 2025-05-12 15:01:30.953968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cabceaa5a966'
down_revision = '2dff249d8e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_tournament_is_default'), 'tournament', ['is_default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_is_default'), table_name='tournament')
    op.drop_column('tournament', 'is_default')
    # ### end Alembic commands ###
