"""Add auto-navigation fields to Tournament model

Revision ID: de039fdee910
Revises: cabceaa5a966
Create Date: 2025-05-18 07:30:35.661271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de039fdee910'
down_revision = 'cabceaa5a966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
